services:
  featureflagservice:
    image: featureflagservice
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_UID: 1000
        VERSION: ${VERSION:-1.0.0}
    volumes:
      - ./.data:/data