x-featureflagservice:
  &default-featureflagservice
  image: kcordes/featureflagservice:latest
  build:
    context: .
    dockerfile: Dockerfile
    args:
      APP_UID: 1000
      VERSION: ${VERSION:-1.0.0}

services:
  featureflagservice-latest:
    *default-featureflagservice
  
  featureflagservice-major:
    <<: *default-featureflagservice
    image: "kcordes/featureflagservice:${MAJOR:-1}"
    
  featureflagservice-minor:
    <<: *default-featureflagservice
    image: "kcordes/featureflagservice:${MAJOR:-1}.${MINOR:-0}"
    
  featureflagservice-patch:
    <<: *default-featureflagservice
    image: "kcordes/featureflagservice:${MAJOR:-1}.${MINOR:-0}.${PATCH:-0}"