services:
  featureflagservice:
    image: featureflagservice
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_UID: 1000
        BUILD_CONFIGURATION: Development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.featureflags.rule=Host(`featureflags.docker`)"
      - "traefik.http.routers.featureflags.entryPoints=web"
      - "traefik.http.routers.featureflags.service=featureflags"
      - "traefik.http.services.featureflags.loadbalancer.server.port=8080"
    networks:
      - traefik
      - default
    environment:
      ASPNETCORE_ENVIRONMENT: Development

networks:
  traefik:
    external: true
