//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommandLineParser_fr_CA {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandLineParser_fr_CA() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Console.Resources.CommandLineParser_fr_CA", typeof(CommandLineParser_fr_CA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string HelpIdOption {
            get {
                return ResourceManager.GetString("HelpIdOption", resourceCulture);
            }
        }
        
        public static string HelpEnableOption {
            get {
                return ResourceManager.GetString("HelpEnableOption", resourceCulture);
            }
        }
        
        public static string HelpListFeatureFlagsVerb {
            get {
                return ResourceManager.GetString("HelpListFeatureFlagsVerb", resourceCulture);
            }
        }
        
        public static string HelpGetFeatureFlagVerb {
            get {
                return ResourceManager.GetString("HelpGetFeatureFlagVerb", resourceCulture);
            }
        }
        
        public static string HelpCreateFeatureFlagVerb {
            get {
                return ResourceManager.GetString("HelpCreateFeatureFlagVerb", resourceCulture);
            }
        }
        
        public static string HelpUpdateFeatureFlagVerb {
            get {
                return ResourceManager.GetString("HelpUpdateFeatureFlagVerb", resourceCulture);
            }
        }
        
        public static string SentenceBadFormatConversionErrorOption {
            get {
                return ResourceManager.GetString("SentenceBadFormatConversionErrorOption", resourceCulture);
            }
        }
        
        public static string SentenceBadFormatConversionErrorValue {
            get {
                return ResourceManager.GetString("SentenceBadFormatConversionErrorValue", resourceCulture);
            }
        }
        
        public static string SentenceBadFormatTokenError {
            get {
                return ResourceManager.GetString("SentenceBadFormatTokenError", resourceCulture);
            }
        }
        
        public static string SentenceBadVerbSelectedError {
            get {
                return ResourceManager.GetString("SentenceBadVerbSelectedError", resourceCulture);
            }
        }
        
        public static string SentenceErrorsHeadingText {
            get {
                return ResourceManager.GetString("SentenceErrorsHeadingText", resourceCulture);
            }
        }
        
        public static string SentenceHelpCommandTextOption {
            get {
                return ResourceManager.GetString("SentenceHelpCommandTextOption", resourceCulture);
            }
        }
        
        public static string SentenceHelpCommandTextVerb {
            get {
                return ResourceManager.GetString("SentenceHelpCommandTextVerb", resourceCulture);
            }
        }
        
        public static string SentenceMissingRequiredOptionError {
            get {
                return ResourceManager.GetString("SentenceMissingRequiredOptionError", resourceCulture);
            }
        }
        
        public static string SentenceMissingRequiredValueError {
            get {
                return ResourceManager.GetString("SentenceMissingRequiredValueError", resourceCulture);
            }
        }
        
        public static string SentenceMissingValueOptionError {
            get {
                return ResourceManager.GetString("SentenceMissingValueOptionError", resourceCulture);
            }
        }
        
        public static string SentenceMutuallyExclusiveSetErrors {
            get {
                return ResourceManager.GetString("SentenceMutuallyExclusiveSetErrors", resourceCulture);
            }
        }
        
        public static string SentenceNoVerbSelectedError {
            get {
                return ResourceManager.GetString("SentenceNoVerbSelectedError", resourceCulture);
            }
        }
        
        public static string SentenceRepeatedOptionError {
            get {
                return ResourceManager.GetString("SentenceRepeatedOptionError", resourceCulture);
            }
        }
        
        public static string SentenceRequiredWord {
            get {
                return ResourceManager.GetString("SentenceRequiredWord", resourceCulture);
            }
        }
        
        public static string SentenceSequenceOutOfRangeErrorOption {
            get {
                return ResourceManager.GetString("SentenceSequenceOutOfRangeErrorOption", resourceCulture);
            }
        }
        
        public static string SentenceSequenceOutOfRangeErrorValue {
            get {
                return ResourceManager.GetString("SentenceSequenceOutOfRangeErrorValue", resourceCulture);
            }
        }
        
        public static string SentenceSetValueExceptionError {
            get {
                return ResourceManager.GetString("SentenceSetValueExceptionError", resourceCulture);
            }
        }
        
        public static string SentenceUnknownOptionError {
            get {
                return ResourceManager.GetString("SentenceUnknownOptionError", resourceCulture);
            }
        }
        
        public static string SentenceVersionCommandText {
            get {
                return ResourceManager.GetString("SentenceVersionCommandText", resourceCulture);
            }
        }
        
        public static string SentenceOptionGroupWord {
            get {
                return ResourceManager.GetString("SentenceOptionGroupWord", resourceCulture);
            }
        }
        
        public static string HelpDeleteFeatureFlagVerb {
            get {
                return ResourceManager.GetString("HelpDeleteFeatureFlagVerb", resourceCulture);
            }
        }
        
        public static string HelpShowConfigVerb {
            get {
                return ResourceManager.GetString("HelpShowConfigVerb", resourceCulture);
            }
        }
        
        public static string HelpShowConfigValue {
            get {
                return ResourceManager.GetString("HelpShowConfigValue", resourceCulture);
            }
        }
    }
}
