//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandLineParser_fr_CA {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandLineParser_fr_CA() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Console.Resources.CommandLineParser_fr_CA", typeof(CommandLineParser_fr_CA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string HelpIdOption {
            get {
                return ResourceManager.GetString("HelpIdOption", resourceCulture);
            }
        }
        
        internal static string HelpEnableOption {
            get {
                return ResourceManager.GetString("HelpEnableOption", resourceCulture);
            }
        }
        
        internal static string HelpListFeatureFlagsVerb {
            get {
                return ResourceManager.GetString("HelpListFeatureFlagsVerb", resourceCulture);
            }
        }
        
        internal static string HelpGetFeatureFlagVerb {
            get {
                return ResourceManager.GetString("HelpGetFeatureFlagVerb", resourceCulture);
            }
        }
        
        internal static string HelpCreateFeatureFlagVerb {
            get {
                return ResourceManager.GetString("HelpCreateFeatureFlagVerb", resourceCulture);
            }
        }
        
        internal static string HelpUpdateFeatureFlagVerb {
            get {
                return ResourceManager.GetString("HelpUpdateFeatureFlagVerb", resourceCulture);
            }
        }
    }
}
