//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_SharedResource_fr_CA {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_SharedResource_fr_CA() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Console.Resources.Localization_SharedResource_fr_CA", typeof(Localization_SharedResource_fr_CA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Error___0__ {
            get {
                return ResourceManager.GetString("Error: {0}.", resourceCulture);
            }
        }
        
        internal static string _false {
            get {
                return ResourceManager.GetString("false", resourceCulture);
            }
        }
        
        internal static string Feature_Flag___0___created_ {
            get {
                return ResourceManager.GetString("Feature Flag \"{0}\" created.", resourceCulture);
            }
        }
        
        internal static string Feature_Flag___0___doesn_t_exist_ {
            get {
                return ResourceManager.GetString("Feature Flag \"{0}\" doesn\'t exist.", resourceCulture);
            }
        }
        
        internal static string Feature_Flag___0___updated_ {
            get {
                return ResourceManager.GetString("Feature Flag \"{0}\" updated.", resourceCulture);
            }
        }
        
        internal static string Id____0____Enabled____1__ {
            get {
                return ResourceManager.GetString("Id: \"{0}\", Enabled: \"{1}\"", resourceCulture);
            }
        }
        
        internal static string _true {
            get {
                return ResourceManager.GetString("true", resourceCulture);
            }
        }
        
        internal static string Unknown_command_ {
            get {
                return ResourceManager.GetString("Unknown command.", resourceCulture);
            }
        }
        
        internal static string Feature_Flag___0___deleted_ {
            get {
                return ResourceManager.GetString("Feature Flag \"{0}\" deleted.", resourceCulture);
            }
        }
    }
}
