name: E2E Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up .Net 8.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.X
          
      - name: Create data folder
        run: mkdir .data

      - name: Run service in SQLITE mode
        run: docker compose -f compose.yaml -f compose.e2e.yaml up -d
        
      - uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: '10'
          
      - run: docker compose -f compose.yaml -f compose.e2e.yaml logs
        
      - name: Test creating a flag
        run: docker compose -f compose.yaml -f compose.e2e.yaml exec featureflagservice console featureflag:create -i "test_flag" -e true
      
      - name: Run tests in SQLITE mode
        run: find *.E2E -maxdepth 0 -type d \( ! -name . \) -exec bash -c "cd '{}' && dotnet test --filter TestCategory=sqlite --logger:\"console;verbosity=detailed\"" \;
        
      - name: Shutdown the service
        run: docker compose -f compose.yaml -f compose.e2e.yaml down
        
      - name: Run service in Split mode
        run: docker compose -f compose.yaml -f compose.e2e.yaml up -d
        env:
          SPLIT__SDKKEY: ${{ secrets.SPLIT__SDKKEY }}
          SPLIT__TREATMENTKEY: default
          
      - uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: '10'
          
      - name: Check the datasource
        run: docker compose -f compose.yaml -f compose.e2e.yaml exec featureflagservice console config:show datasource
        
      - name: Run tests in Split mode
        run: find *.E2E -maxdepth 0 -type d \( ! -name . \) -exec bash -c "cd '{}' && dotnet test --filter TestCategory=split" \;
      
      - name: Shutdown the service
        run: docker compose -f compose.yaml -f compose.e2e.yaml down