name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Generate next version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main

      - name: Parse semver string
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ steps.semver.outputs.next }}
          
      - name: Build images
        run: |
          echo "VERSION=${{ steps.semver.outputs.nextStrict }} MAJOR=${{ steps.semver_parser.outputs.major }} MINOR=${{ steps.semver_parser.outputs.minor }} PATCH=${{ steps.semver_parser.outputs.patch }} docker compose -f compose.build.yaml build"
          VERSION=${{ steps.semver.outputs.nextStrict }} MAJOR=${{ steps.semver_parser.outputs.major }} MINOR=${{ steps.semver_parser.outputs.minor }} PATCH=${{ steps.semver_parser.outputs.patch }} docker compose -f compose.build.yaml build
        
      - name: Log into DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push up the images
        run: VERSION=${{ steps.semver.outputs.nextStrict }} MAJOR=${{ steps.semver_parser.outputs.major }} MINOR=${{ steps.semver_parser.outputs.minor }} PATCH=${{ steps.semver_parser.outputs.patch }} docker compose -f compose.build.yaml push
        
      - name: Publish the DockerHub readme
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASS }}
        with:
          destination_container_repo: kcordes/featureflagservice
          provider: dockerhub
          short_description: 'Feature flag microservice'
          readme_file: 'DOCKERHUB-README.md'
          
      - name: Tag
        run: git tag ${{ steps.semver.outputs.next }} && git push origin ${{ steps.semver.outputs.next }}
        
      - name: Generate changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ steps.semver.outputs.next }}
          writeToFile: false
          
      - name: Create release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ steps.semver.outputs.next }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}
          tag: ${{ steps.semver.outputs.next }}